export default [
  { label: 'Status', field: 'status' },
  { label: 'Name', field: 'name' },
  { label: 'Dept', field: 'dept_num_sec' },
  { label: 'Days', field: 'days' },
  { label: 'Gereqs', field: 'gereqs' },
  { label: 'Days', field: 'days' },
  { label: 'Times', field: 'times' },
  { label: 'Prof', field: 'prof' },
  { label: 'Rating', field: 'rating' },
  { label: 'Difficulty', field: 'difficulty' },
  { label: 'Reviews', field: 'reviews' },
  { label: 'Prereqs', field: 'has_prereqs' },
  { label: 'Actions', field: 'actions' },
]